
@user = User.create username: "testy", email: "test@test.com", password: "password", password_confirmation: "password"

@article1 = Article.create name: "Lawnbot400", description: 'The lawnbot400 is a remotely controlled lawnmower that can mow your grass while you sit in the comfort of your home. This was my first real robotic project that I used the Arduino for, and it has evolved from a fun project into my most frequently used yard-tool. With a run time of about 6 hours straight, it usually has enough power to mow my entire yard twice between charging. I currently use this bot to mow my grass about every 2 weeks in the summer, and have now for about 2.5 years. The mower deck is an old Weed-Eater brand 22" push mower, so it will run as long as it has gas in the tank. I have added several additional accessories to the frame to make it more useful, like a set of headlights, a kill switch, and a wheel-barrow bucket on top with a motorized lift - all of which are operated remotely. If at any time, I feel like the Lawnbot is getting too close to something or it stops responding to my inputs, I can flip a kill switch on the R/C transmitter that will disable all movement on the bot - this failsafe also kicks in automatically if the bot gets out of range or the battery dies on the transmitter. The Lawnbot400 has been featured on the cover of MAKE magazine issue 22, mentioned in Wired Magazine (the one with LadyAda on the cover), featured on Instructables.com (twice), it was in a feature article for my old college alumni magazine (UAB), and was included in my recent book "Arduino Robotics" as the chapter 10 project. While the plans for the Arduino are free, I plan on building kits for the lawnbot so you will soon be able to get your own, even if you dont want to build it from scratch... Stay tuned! ', user_id: @user.id, image: File.open(File.join(Rails.root, "db", "seeds", "images", "image1.jpg")), featured: true, published: true


@article2 = Article.create name: "Arduino Robotics", description: "I recently wrote a book titled 'Arduino Robotics' that goes into some of the fundamentals of electricity and electronics, followed by a couple of chapters on how the Arduino works with motors and sensors, and finally a collection of 10 robotics projects, all of which use the Arduino. While some of the projects can get pretty hands-on, they are (hopefully) simplified to be easier to understand, cutting out as much of what is not needed as possible. I plan on this website being a place for readers to interact by posting on the forum (coming soon) to ask a question or share an idea, posting pictures and a description of a robot that you built from the book, and soon have robot parts (and kits) available to buy for the book projects. Check it out here: http://www.amazon.com/Arduino-Robotics-ebook/dp/B005PZ28WI", user_id: @user.id, image: File.open(File.join(Rails.root, "db", "seeds", "images", "image2.jpg")), featured: true, published: true


@tutorial1 = Tutorial.create name: "How to build a robot", category: "robotics", description: "This is the first test tutorial. It is not going to teach you anything, but it will give me something to read and look at while I am developing my web site. If you do not agree with this tutorial, that's too bad. This is the end of the description", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image6.jpg"))
@tutorial1.steps.create name: "Do something", step_number: "Step 1", description: "This is step number 1 from tutorial number 1. you should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image4.jpg"))
@tutorial1.steps.create name: "Do something else", step_number: "Step 2", description: "This is step number 2 from tutorial number 1. You should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image5.jpg"))
@tutorial1.steps.create name: "Do something a third time", step_number: "Step 3", description: "This is step number 3. you should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image6.jpg"))


@tutorial2 = Tutorial.create name: "Beginning Electronics", category: "electronics", description: "This is the first test tutorial. It is not going to teach you anything, but it will give me something to read and look at while I am developing my web site. If you do not agree with this tutorial, that's too bad. This is the end of the description", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image7.jpg"))
@tutorial2.steps.create name: "Do something different", step_number: "Step 1", description: "This is step number 1 from tutorial 2.. you should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image7.jpg"))
@tutorial2.steps.create name: "Do something different again", step_number: "Step 2", description: "This is step number 2 from tutorial 2. you should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image8.jpg"))
@tutorial2.steps.create name: "Do something different a third time", step_number: "Step 3", description: "This is step number 3. you should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image9.jpg"))


@tutorial3 = Tutorial.create name: "Building a website", category: "web", description: "This is the first test tutorial. It is not going to teach you anything, but it will give me something to read and look at while I am developing my web site. If you do not agree with this tutorial, that's too bad. This is the end of the description", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image10.jpg"))
@tutorial3.steps.create name: "Do something different", step_number: "Step 1", description: "This is step number 1 from tutorial 2.. you should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image10.jpg"))
@tutorial3.steps.create name: "Do something different again", step_number: "Step 2", description: "This is step number 2 from tutorial 2. you should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image11.jpg"))
@tutorial3.steps.create name: "Do something different a third time", step_number: "Step 3", description: "This is step number 3. you should explain how to do stuff here", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image12.jpg"))


@project1 = Project.create name: "The Lawnbot400", description: "The lawnbot400 is a remotely controlled lawnmower that can mow your grass while you sit in the comfort of your home. You can add a camera, GPS, or any number of other options to make your lawnbot more dangerous. This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "robotics", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image13.jpg")), user_id: User.first, :published => true
@project2 = Project.create name: "The Segbot", description: "The seg-bot is a diy segway clone that can transport a human for more than 3 hours straigh. It is my primary mode of transportation in my basement when I am going to get a drink from the fridge. This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "electronics", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image14.jpg")), user_id: User.first, :published => true
@project3 = Project.create name: "The Battlebot", description: "The battle-bot is a diy fighting robot whose sole purpose is to destroy it's opponent.This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "web", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image15.jpg")), user_id: User.first, :published => true

@project4 = Project.create name: "Wally", description: "The lawnbot400 is a remotely controlled lawnmower that can mow your grass while you sit in the comfort of your home. You can add a camera, GPS, or any number of other options to make your lawnbot more dangerous. This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "ultrasonic", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image13.jpg")), user_id: User.first, :published => true
@project5 = Project.create name: "Electric Fishing pole", description: "The seg-bot is a diy segway clone that can transport a human for more than 3 hours straigh. It is my primary mode of transportation in my basement when I am going to get a drink from the fridge. This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "outdoors", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image14.jpg")), user_id: User.first, :published => true
@project6 = Project.create name: "Traffic Light", description: "The battle-bot is a diy fighting robot whose sole purpose is to destroy it's opponent.This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "web", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image15.jpg")), user_id: User.first, :published => true

@project7 = Project.create name: "Toy Car", description: "The lawnbot400 is a remotely controlled lawnmower that can mow your grass while you sit in the comfort of your home. You can add a camera, GPS, or any number of other options to make your lawnbot more dangerous. This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "repurposed", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image13.jpg")), user_id: User.first, :published => true
@project8 = Project.create name: "Chicken Coop", description: "The seg-bot is a diy segway clone that can transport a human for more than 3 hours straigh. It is my primary mode of transportation in my basement when I am going to get a drink from the fridge. This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "robotics", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image14.jpg")), user_id: User.first, :published => true
@project9 = Project.create name: "RFID", description: "The battle-bot is a diy fighting robot whose sole purpose is to destroy it's opponent.This machine is so dangerous in fact, that users are currently limited to those who can understand its workings enough to build one.", category: "electronics", image: File.open(File.join(Rails.root, "db", "seeds", "images", "image15.jpg")), user_id: User.first, :published => true

